import React from 'react';
import Image from '../tags/img';
import Link from '../tags/link';
import QuoteStub from '../tags/quote_stub';


class Airlines extends React.Component {
    constructor(props) {
        super(props)
    }

    render() {
        return (<div className="article-wrapper">
            <br/>With airline stocks in precipitous decline and details of a bailout being hammered out this minute, I've spent the past two weeks trying to better understand the longer-term profitability (or lack thereof) of the airline industry.  Warren Buffett, America's favorite ruthless grandfather, famously joked about the airline industry in 2008:
            <QuoteStub quotedText="Here a durable competitive advantage has proven elusive ever since the days of the Wright Brothers. Indeed, if a farsighted capitalist had been present at Kitty Hawk, he would have done his successors a huge favor by shooting Orville down." />
            I like to describe airlines as a capacity-commodity industry:  profitability of the industry rests primarily not on the growth of the underlying market (the demand for travel), but on limiting supply (in this case, the number of airplane seats in the air) to maintain pricing.
            <br/><br/>We see this precarious dynamic across many capacity-commodity industries:  companies carefully expand production capacity, wary of sparking build-out wars.  Samsung, commenting most recently on their Q4 earnings call, would rationalize their expansion of NAND (the chip used in solid-state drives) capacity very carefully, trying not to scare competitors into believing there would be industry oversupply:
            <QuoteStub quotedText="Regarding our investments going forward, the base that we are operating in is that the demand we're expecting, as we mentioned during the presentation, is around mid-10% growth for DRAM and mid to high-20% growth for NAND. Basically, our default is to meet the demand growth through process migration as well as using our inventory. 
            Now to answer the hypothetical question that you posed about, for example, this year, demand going far over what's expected overall, then we will have the option, for example, to respond to market demand flexibly using Phase 2 of Pyeongtaek or Phase 2 of Xi'an, these new fabs, so that would be an option in that situation that you've proposed." />
            Notice what Samsung is actually saying here: "We can meet some demand through process node migration (Moore's Law), and we did kind of overproduce last quarter, so we have these leftover NAND chips and we'll sell those too.  Oh by the way, let's just address this hypothetical question you've asked, for which we've already spent $2.3bn USD, that if demand were higher, we would produce more. Hypothetically.  Not saying we're doing it, even though the fab is already online, just that we're ready."
            What's worse, SK Hynix (the other leading NAND manufacturer) says much of the same thing: "We'll produce more...if there's more demand!" The two companies try to maintain face in the market by signalling a somewhat cooperative environment, while simultaneously attempting to sneak away and grab a little bit of market share. Everyone is trying to cheat their way, just a little bit, to higher profitability.  As Samsung and SK Hynix demonstrate, all capacity-commodity industries are really multi-billion dollar games of <Link href="https://www.urbandictionary.com/define.php?term=Just%20the%20tip">"just the tip"</Link>.
            <br></br><br/>Similar to the NAND industry, which consolidated from five major players to four after the implosion of Elpida, the merger of Continental Airlines with United Airlines in 2010, and the merger of US Airways with American, shrank airline the industry to three large players (United, American, and Delta), with four tiny players (JetBlue, Southwest, Spirit, and Virgin) resulting in route consolidation and highly-profitable small-airport destinations (i.e., a flight to Buffalo NY has a higher price-per-mile than a flight to Chicago).
            <br/><br/>Buffett describes this industry consolidation and collusion in his typical bullshit-folksy way, after taking an 11% stake in Delta Airlines: <QuoteStub quotedText="It’s true that the airlines had a bad 20th century. They’re like the Chicago Cubs. And they got that bad century out of the way, I hope."/>
            I really hope to one day learn to communicate in the non-threatening way that Buffet does (Magic 8-Ball says: "Outlook not so good."):  he manages to entirely elide the overwhelming tendency of oligopolies to engage in widespread price and capacity collusion.
            <br/><br/>There are a bunch of subtle ways that airlines can collude to restrict capacity.  One approach, as alluded to by Delta in what I can only describe as the greatest big-brain-energy play in the history of collusive behaviors is as follows:
            <QuoteStub quotedText="We at Delta were the only airline back in 2012 that voluntarily capped our carbon footprint at 2012 levels." />
            This is an evil-genius-level play. Since emissions are primarily driven by fuel consumption and fuel efficiency, Delta is de-facto signalling capacity restriction by signalling carbon footprint restriction.  These people are evil geniuses, for managing to combine eco-friendly virtue-signalling with industry collusion, all in one neat, tidy, totally legally defensible claim that probably can't be litigated against.
            <br/><br/>Another (arguably) legally-defensible approach would be for all airlines to pledge 85% of their earnings to dividends:  airlines that cut their dividend (in order to grow fleet size), would see their stock immediately punished (since their dividend was cut), and dividends of this magnitude would prevent fleets from growing, thereby enabling stable industry capacity and profitability.  Dividends would have the added benefit of preventing poorly timed share repurchases: the fact that UAL and DAL have cut share repurchases exactly when their stocks are cheapest is all I need to say here.
            <br/><br/>Unfortunately for shareholders, airline CEOs are generally paid in options (which don't pay a dividend), and therefore, airline CEOs have a tendency to favor share buybacks, which, if you recall from our article <Link href="/stonks">"How to be a shitty investor"</Link>, are only good in limited circumstances.
            <br/><br/>The biggest driver of airline capacity however, is no longer fleet size, capital allocation decisions, or emissions, but airport landing and takeoff slots:  the scheduled time a flight is allowed to arrive and depart at a specific hub. These slots are effectively "timeshares" in the literal sense, and are owned by a specific airline, while being sold/coordinated by airports. 
            <br/><br/>Most US airports are near-capacity, so for an airline to gain a foothold in a new hub, an existing airline must approve it. This obviously leads to incredibly profitable horse-trading shenanigans (the horses are airport slots):  like collecting specific properties in Monopoly, airlines will trade slots until a duopoly of airlines control the slots at each airport.  This game of Monopoly even has a name: "hub premium", the higher price that passengers tend to pay when an airline has consolidated a significant percentage of overall slots at a single airport.
            <br/><br/>Hub premiums and slotting are the real reason Buffett loves airlines:  in good times, they can no longer be their own worst enemy, and are limited in capacity expansion through limited airport slots, and can even gain extraordinary pricing power in hubs they control (some online whitepapers have shown that the hub premium can be as high as 10-20%, which is effectively the entire profitability of the industry).
            <br/><br/>In 2000, the Wendel H. Ford Aviation Investment and Reform Act for the 21st Century (Air-21) attempted to curb this behavior and attempted to ensure that new entrants had ample access to airport facilities and slots, stating that "major airports must be available on a reasonable basis to all air carriers wishing to serve those airports".
            <br/><br/>In order to encourage airports' cooperation in opening up airports to "all air carriers wishing to serve those airports", Congress made federal sources of funding contingent on compliance: blocking passenger facility fees (up to $4.50 per ticket) in government subsidies should an airport fail to comply.  Note that these fees would go to the airport, not the airline, as obviously airlines would otherwise happily eat a $4.50 loss to reprice by an extra $100-$200.
            <br/><br/>Unfortunately for consumers, this law only applies when an airport is responsible for "over 0.25% of all enplanements", which means that smaller US airports are incredibly profitable for incumbent carriers that have no requirement to give up their slots.
            <br/><br/>Analysts ask about slots on conference calls, and you should notice from the following JetBlue earnings call how closed-lipped leadership is being here: no carrier wants to tip their hand on how negotiations are proceeding. 
            <br/><br/>Hunter Keay of Wolfe Research to JetBlue management: <QuoteStub quotedText="...can you update us and where you are on obtaining slots?"/>
            Stephen Priest, JetBlue CFO: <QuoteStub quotedText="Again, I'll pick up the aircraft side of things. And then I'll get Joanna to give an update on the wider perspective with regard to slots. We remain confident in our plans to continue to grow relevance in both New York and Boston with the European expansion. Great amount of planning underway and again because of the close cooperation with Airbus we are confident with the delivery timeframes around the A321. So I'm going to Johanna to give a better perspective in terms of - our perspectives in terms of slots et cetera." />
            Joanna Geraghty, JetBlue COO: <QuoteStub quotedText="...We continue to work multiple paths around slots and a number of London area airports were confident that our London plans can work in any number of airports. And we'll update you when we have a bit more information to share."/>
            The New York Times has some interesting stories showing how incredibly hard it is to break into an airport for a marginal player: <QuoteStub quotedText="Virgin, for instance, has found it difficult to expand in big airports controlled by its rivals. The carrier tried for three years to get into Chicago O’Hare International Airport, where United and American Airlines own most of the gates and would not part with them. Eventually, the airport bought a concourse once operated by Delta and opened it to new entrants, allowing Virgin to establish six flights a day between Chicago and San Francisco.
            “They weren’t interested in another competitor,” said David Cush, Virgin America’s president.
            But Virgin is still finding it hard to get landing slots at Newark Liberty International Airport, controlled by United. As part of its merger with Continental, United sold some landing and takeoff slots in a private sale to Southwest Airlines that left Virgin out of the loop. As a result, United is still the only airline to offer a direct route between Newark and San Francisco." />
            You'll also notice from that article that only marginal airlines like Virgin are willing to comment: slot control is so important to major players that their representatives generally avoid all comment. <br/><br/> Slots appear to be the most strategically important property of an airline: they inherently restrict airlines from competing each other to death.
            Buffett is right as usual: the first 100 years of airline growth were uncapped by airport slot constraints, which are now preventing airlines from becoming their own worst enemy.  To the upside, I see an enormous opportunity for airlines to be far more shareholder-friendly by enacting aggressive capacity restraint through dividend signalling and carbon emission control.  To the downside, airlines will continue to face more regulation: airlines touch a broad base of political constituents and their long-term profitability is fundamentally capped by consumer ire and regulatory oversight.
            <br/><br/>If you've ever wondered if antitrust regulation is truly helpful, consider this:  Berkshire Hathaway has over $124bn in cash or T-bills, and without regulation Buffett could trivially acquire all five US airlines with no external financing, consolidating airport slotting across every airport and gaining monopolistic pricing (I can hear Warren's heavy breathing), and single-handedly float their working capital needs.  With regulation, new entrants will be able to gain footholds and compete if pricing gets too far out of wack.  Ultimately, the answer to the question of long-term US airline profitability rests almost exclusively on regulatory oversight: with peak travel demand in non-Corona times exceeding airport capacity, US airlines will be as profitable as they can get away with. 
           <br/><br/><b>Are airline stocks worth owning, right now?</b>
           <br/><br/> The airline bailout memo paints the exact picture we would imagine:
           <QuoteStub quotedText="Pessimistic: $26B (67%) net drop in liquidity for A4A passenger carriers alone in the first 6 months of
                                2020 to $12.8B. By end of 2020, they will have dropped $53B (135%) to a deficit of negative $14B.
                                In this scenario, all seven of A4A passenger carriers run out of money completely sometime
                                between June 30 and the end of the year. Making matters even more urgent, credit card
                                companies would likely begin withholding cash from sales before the carriers actually run out of
                                money, effectively causing carriers to run out of money earlier than June 30." />
            Credit card companies "witholding payment" to the major airlines is an absolutely blood-chilling statement. There really is no precedence for this situation:  in 2009, Delta still served 188bn revenue passenger miles with 82% passenger load. At its peak in 2019, Delta will do 237bn revenue passenger miles.  We have literally <i>never</i> seen a true decline in air travel in the US, not even from 9-11.  However, we do have real data, from Chinese airlines, for this exact crisis!
            <br/><br/><b>China Southern Airlines March 18 Press Release:</b>
            <QuoteStub quotedText="In February 2020, the Group actively responded to changes in market demand, timely adjusted its
                                operation strategy, optimized its capacity allocation and reduced some flights. Passenger capacity
                                (measured by available seat kilometres (“ASK”)) of the Group decreased by 73.07% as compared
                                to the same period last year (a year-on-year (“YoY”) basis). Of which, passenger capacity for
                                domestic, regional and international routes decreased by 74.31%, 91.05% and 69.34%,
                                respectively as compared to the same period last year. Compared to the same period last year,
                                passenger traffic (measured by revenue passenger kilometres (“RPK”)) decreased by 85.11%. Of
                                which, passenger traffic for domestic, regional and international routes decreased by 85.95%,
                                95.92% and 82.69%, respectively as compared to the same period last year. The passenger load
                                factor was 47.11%, representing a decrease of 38.11 percentage points as compared to the same
                                period last year. Of which, the passenger load factor for domestic, regional and international
                                routes decreased by 38.77 percentage points, 41.86 percentage points and 36.92 percentage points,
                                respectively, as compared to the same period last year." />
            Holy shit.  This is awful. An 85% decline of revenue passenger kilometers for passenger flights.  There is almost no way the US airlines get out of this without massive shareholder dilution in addition to loan guarantees.  I am likely not a buyer at $20/share for Delta, the largest and best-run of the airlines.
            <br/><br/>While Delta is better-positioned than United, <b>their working capital "backdraft" is simply too high</b>: <u>flight refunds will absolutely devastate their liquidity</u>. Delta had $47bn of annual revenues in 2019, so consider the possibility of Delta seeing $5bn-$20bn of pending refund requests (my wild-ass guess) while having only $2bn of cash for refunds, and $40bn of opex ($11bn of which is salaries, and $2bn of which are landing fees), the fixed costs of Delta still massively outweigh existing liquidity: I estimate the working capital suck to be so high that Delta and others may need a second bailout should this disaster last 18 months.
            <br/><br/>Airlines are sort of like very fragile insurance companies or banks:  they float/"lend" an enormous amount of money ($50bn of revenues / $44bn opex for Delta) while being worth very little (Delta is valued at $13bn on the day of this writing). Airlines have been walking a very wobbly tightrope over the past 5 years, and falling off has meant a $50bn federal bailout, which vastly exceeds the amount the industry used to repurchase shares over the last 4 years.  Airline profits should be tucked away for leaner times, but instead are wasted on overvalued shares, making their share price rise almost illusory.
            <br/><br/>Ironically, the US Federal bailout's plan to block stock buybacks for US airlines should actually be great for investors in the long-run: were someone to buy shares today and hold until results normalized, airlines will be able to return cash to shareholders at <u>incredibly</u> high yields (as a percentage of cost basis).  Delta prints $7/share in earnings in a peak year but pays only $1.50 in dividends.  Post-bailout, we can imagine Delta's share count doubling (and share prices halving) from massive equity dilution.  Imagine a world where Delta is forced to distribute $3.50 a share in dividends on after you paid only $5-$10 a share.
            <br/>
            <Image widthOverride="500px" src="https://ei.marketwatch.com/Multimedia/2015/04/30/Photos/ZQ/MW-DK909_buffet_20150430101837_ZQ.jpg?uuid=dd3e11c8-ef43-11e4-b07f-9b20ed70af1b" />
            One can only dream.
            <br/><br/>I'm a buyer of post-bailout DAL at $8/share.
        </div>)
    }
}

export default Airlines;