import React from 'react';
import Image from '../tags/img';
import Link from '../tags/link';
import QuoteStub from '../tags/quote_stub';

class LBrands extends React.Component {
    constructor(props) {
        super(props)
    }

    render() {
        return (<div className="article-wrapper">
            <br/>Joel Tillinghast, a once-legendary portfolio fund manager and colleague at Fidelity, sometimes describes retail apparel investing as "momentum-based". After all, when it works, you look like a genius: people throw $20 bills at you in exchange for flimsy cotton shifts that cost $3.50 to manufacture and $5 to market.
            Every appareler is convinced they have the Midas touch, and <Link href="https://en.wikipedia.org/wiki/Forever_21">when it stops working</Link>, the public reacts to the your brand as if they'd awakened in some haze: "Why did we buy this stuff to begin with?" consumers wonder.
            "Why did we give this thing such a high multiple?" investors wonder.  Somehow, we never learn the lesson with apparel, and so the cycle continues. <br/>
            <br/>There's a subtle distinction I'd like to make, though. While "momentum" is a good first-order approximation, it doesn't really describe what's actually going on: a realization gradient.  Consumers over time realize the social capital that's being conveyed through apparel, and buy it because they come to an understanding.  The realization gradient works both ways: some consumers are less quick to realize the death of a brand, but they eventually catch on and stop buying as well.  The belief that apparel is a random walk down human preferences isn't accurate: rather, the social-capital zeitgeist shifts over time, and brands that are well-positioned to trade on that social capital do well.
            <br/><br/>Victoria's Secret is entering the negative realization death spiral.  The clothing is now perceived as uncomfortable, overpriced vs alternatives, and promoting unhealthy expectations. Les Wexner's <Link href="https://www.vox.com/the-goods/2019/7/10/20689134/jeffrey-epstein-les-wexner-l-brands-victoria-secret-limited">Epstein connection</Link> is certainly not helping.  The optics are horrendous.  What was once sexy is now complicit.  Worse, there are far, far too many competent competitors.  Let's review.
            <br/><br/>Gap Body has been exceptionally successful at targeting lingerie "basics".
            <Image href="https://img.huffingtonpost.com/asset/596fc90a2100003700fc7c4a.png?ops=scalefit_720_noupscale" />
            <br/><br/>Journelle and Nordstrom round out the midtier:
            <Image href="https://i.imgur.com/fOcRTbw.png" />
            <Image href="https://i.imgur.com/0UhKx1l.png" />
            <br/><br/>Agent Provocateur and La Perla round out the high end.
            <Image href="https://i.imgur.com/nKQUslB.png" />
            <Image href="https://i.imgur.com/3AJ1SIc.png" />
            Don't even get me started on the infinity of online competitors -- Adore Me, Panache, Hanky Panky, Heidi Klum Intimates, Mapale, Yummie, Addiction Nouvelle, Parfait, Le Mystere, Montelle Intimates, Giapenta, and Cosabella turn up with a few seconds of searching.  Victoria's Secret is deader-than-dead, and worse yet, has massive operating leases and a fleet of retail sales associates that will accelerate its demise.
            To be honest, I've never understood how lingerie at Victoria's Secret became such a dominant in-store purchasing phenomenon to begin with:  the shopping experience for men is at best awkward, and for women the brand is currently perceived as regressive, uncomfortable, and sexist.  
            I'd also argue that the competition is broader than we realize: various athleisure brands fulfill a similar body-positivity drive while mitigating any feelings of being <Link href="https://www.forbes.com/sites/pamdanziger/2018/11/25/thirdlove-tells-john-mehas-how-to-fix-victorias-secret-in-full-page-new-york-times-ad/#292449f72285">complicit</Link>.
            Limited Brands will of course cut non-performing VS stores, but the question is how fast?
            <br/><br/>There's an inherent tension between bondholders and equity holders here:  Les Wexner owns 17% of the outstanding equity, his wife owns another 5%, and will issue dividends until it becomes <Link href="https://www.investopedia.com/terms/f/fraudulentconveyance.asp">fraudulent conveyance</Link> to continue to do so.  The fact that any dividends are being issued while a). the company needs to cut leases b). the company holds >$5bn in debt yielding 6%+ and c). sales are imploding demonstrates either incompetent corporate finance or denial on the part of Les Wexner.
            If US creditor protection were stronger, bondholders might be able to fire off warning letters now asking Limited Brands leadership to start cutting leases, paying down debt, and halting dividend issuance.  As it stands now, the only thing bondholders can do is sit back and record grievances until Chapter 11 gets filed.
            <br/><br/>I see only one way Limited Brands can pull itself out of this mess: Grow Bath & Body Works fast enough to offset Victoria's Secret losses, and cut VS costs rather than trying to save a dead brand on the wrong side of the realization gradient.
            <QuoteStub text={`"Their target is what we call the mastige segment," she continues. "It's not prestige and it's not mass—it's really about figuring out this niche of very American-centric shoppers that wants a notch above drugstore brands, but are still quite conscious. They don't want the prestige segment, which is where the Estée Lauders and the L'Oreals of the world play."
                                A compelling factor here is the price point. The largest size room spray (5.3 ounces) is only $9.50; foam soaps are $5.50; fragrance mists are $14. You can buy one item from every major category and barely spend $100.
                            Kang confirms that's a huge part of the appeal. She says the diehard fan "is someone who just absolutely loves fragrances, and sees fragrance as an essential part of her lifestyle." She adds, "A lot of our customers actually own multiple fragrances, and they engage in fragrance the way that they do other fashion items in their life. It's a way to accessorize their style. It's not this sort of serious, deep-commitment kind of purchase that you see with a more traditional model in a department store."`} />
            What I like about Bath & Bodyworks is that what they sell is defensible: most "nice things" are expensive for most Americans, whereas Bath and Body Works offers an affordable, guiltless, if synthetic form of self-care.  
            The guiltlessness of the brand is the ultimate growth driver:  its products are sweets-adjacent (notice how many of the candles below are food-oriented), and inexpensive.  Most activities I personally enjoy are either expensive enough to induce some amount of guilt, or unhealthy enough to do the same.  There are almost no "free pleasures" -- an inexpensive scent from Bath & Body Works might be one of the few. I think this is ultimately what's giving Bath & Body Works its incredible comps, and being scent-based, it's of course naturally resistant to online competition.
            <Image href="https://i.imgur.com/QDqwLg3.png" />
            Here's a model of my best guess of what will happen (click on the image so you don't have to squint).  There are a couple noteworthy things here:
            <Image href="https://i.imgur.com/aNzaX9y.png" />
            <br/><br/>1). VS has not yet signficiantly cut non-lease SG&A -- in fact it appears to still be growing in the low-single digits.  This is totally unacceptable and honestly shows that LB management is either delusional or incompetent:
            if your revenues are declining 8% a year and you somehow find a way to grow SG&A, you are either flailing, an imbecile, or a flailing imbecile.  My guess, after having worked at many companies, is that Limited Brands management never set up the kind of performance-attribution tracking necessary to intelligently allocate capital.  Their internal planning is likely just budget-based departmental fights.
            What's worse, new CEO Mehas is likely ride-or-die on Victoria's Secret: so long as he continues to describe his job as "listening to the consumer", rather than "tying a tourniquet", I expect SG&A to be flat at best.  There's also the "stubborn founder" angle -- for Les Wexner to order Mehas to cut VS would be a repudiation of his life's work.  Old billionaires tend to get very sticky, and given Wexner's affiliations with Epstein, doubly so.
            <br/><br/>2). Various gross margins have been adjusted -- many non-cash impairments are negatively impacting earnings in a way that is irrelevant to the business.
            <br/><br/>3). Store leases are typically around 10 years long and non-cancellable, but management is only cutting total VS store square footage by around 3% a year, which means it's only closing around 30% of available "closeable" stores.  This is not remotely aggressive enough.  Management should be aggressively negotiating subleases and taking lease break restructuring impairments on their worst-performing stores.  They should also avoid opening new stores, especially not ones in <Link href="https://tietheknot.scot/the-first-victorias-secret-store-in-scotland-opens-today/">nearly-Brexit</Link> Scotland.  I mean really, what is Les Wexner thinking?
            <br/><br/>4). While I continue to model growth in Bath & Body Works, I think we are close to hitting a wall on growth:  most women I know consider the brand to be for tweens and low-income young mothers.  There's also minimal international appeal -- this is a niche brand for middle American women that is nearing saturation.  Even if we assume 50m American women buy $100 a year of the stuff, that still only gets us $5bn of annual revenues.  I think we are very close to hitting a wall in overall appetite unless Bath and Body Works can find some new realization gradient with very different demographics.
            <br/><br/>5). VS sales and gross margin decline comes almost completely from promotions, aka price cuts.  VS will likely struggle to keep gross margins above 30% in the future.
            <br/><br/>6). I really want to emphasize how much the core of this conflict is fundamentally about <u>capital structure ownership</u>: equity performance via leveraged SG&A, versus debt de-leveraging via decreased SG&A.  Non-rent SG&A is the single largest controllable driver of VS operating profits. Yes, the <Link href="https://variety.com/2019/tv/news/victorias-secret-fashion-show-canceled-why-1203413186/">fashion show was cancelled</Link>, but it's not enough: literally the entire company hinges on whether it can cut SG&A or not -- by 2025 VS will be 0% operating margins from VS declines, even if they manage to reverse SG&A growth and cut it by 3%.  Dramatic restructuring will be necessary to save Limited Brands. <br/>
            <br/> Personally, I am going to own a small holding of LBrands bonds:  it doesn't look like the company as a whole will become insolvent by 2027, whereas the stock will almost certainly be unable to avoid a complete implosion in a few years, so I am planning on shorting 1/3 of the amount of my bond holdings amount in equity.  The goal here is to target a very narrow, carefully modeled valuation range of stub equity value mismanaged by thumb-sucking leadership that will pull themselves out of a crisis only when things get dire.
        </div>)
    }
}

export default LBrands;